export { Navbar } from './navbar'
export { Footer } from './footer'
export { HeroSection } from './hero-section'
export { ServicesGrid } from './services-grid'
export { AIWorkflow } from './ai-workflow'
export { CaseStudiesPreview } from './case-studies-preview'
export { Testimonials } from './testimonials'
export { FAQSection } from './faq-section'
export { AnimatedGradient } from './animated-gradient'
export { OrganizationSchema, WebsiteSchema } from './schema-org'